### ISSUE TITLE
Set Up Digital Workspace

### ISSUE THREAD

**Issue by Langutang** [Project-Rocket-IO/project-rocket-io.github.io#1]
Going to need a place for just holding all the issue information above - google, sharepoint, box, any other cloud provider. Maybe even a discord for chat? Then not flooding text messages with updated

**Comment by Langutang** [comment]
lol this is more of a @beangirlie thing I, goes hand-in-hand with twitter

**Comment by Langutang** [comment]
Documents / Legal / Presentations / Material and Media - google, sharepoint, box, any other provider
Communication / Updates / Project Management - Slack, discord, instant messenger 'you've got mail!'

**Comment by chewylang** [comment]
I can create workspace under the rocketpsa.com domain in Google domains, which will give us working emails, G-suite features and what not (can also set it up under MS if we want the office suite). 

For documentation/project management confluence and Jira are my typical go-tos.
