### ISSUE TITLE
Legal Structure for LLC

### ISSUE THREAD

**Issue by Langutang** [Project-Rocket-IO/project-rocket-io.github.io#2]

**Comment by hstriano** [comment]
General Structure complete
https://www.incfile.com/ - upon agreement will file Multi-Member LLC as Rocket PSA LLC.
Total Cost: $330
- includes state filing costs, business tax consultation, operating agreement, EIN tax number, 1-year free registered agent service, small business banking account set up.

Details on rolling up Rocket PSA into Lang Industries:
https://www.legalzoom.com/articles/can-an-llc-own-another-llc
