### ISSUE TITLE
Brand Kit (Colors & Fonts) Review

### ISSUE THREAD

**Issue by chewylang** [Project-Rocket-IO/project-rocket-io.github.io#21]

**Comment by Langutang** [comment]
This is for the website

**Comment by hstriano** [comment]
Canva Brand Kit:

https://www.canva.com/design/DAFV4qVyfQA/l3LPTk1AVycfJFVJlUTNRg/edit?utm_content=DAFV4qVyfQA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by Langutang** [comment]
fixes #21
