### ISSUE TITLE
Mission Statement Draft

### ISSUE THREAD

**Issue by Langutang** [Project-Rocket-IO/project-rocket-io.github.io#5]

**Comment by hstriano** [comment]
Mission Statement
Lang Industries
At Lang Industries our mission is to reinvent business enablement technology, to offer comprehensive and flexible solutions, to invent and innovate in the spaces plagued with inefficiencies, and to above all else, put the customers needs first. 
Rocket PSA
Our mission is to reinvent business enablement technology with comprehensive and flexible service offerings. To rewrite the script and produce simpler and smarter PSA tools.
