### ISSUE TITLE
Insurance Policies

### ISSUE THREAD

**Issue by Langutang** [Project-Rocket-IO/project-rocket-io.github.io#6]

**Comment by hstriano** [comment]
DO NOT PURCHASE UNTIL BUSINESS IS RUNNING
https://www.thehartford.com/small-business-insurance
Small Business Insurance Policy Quote:
$1,000/year
Including General Liability Coverage and Professional Liability Coverage.
General Liability: Relevant coverage includes lawsuits against the company, damage to company property (computers, terminals, data centers), and customer/client law suits
Professional Liability: Protects against data breaches, not meeting service requirements, accounting errors, negligence, misrepresentation, or inaccurate advice that may lead to law suits
