### ISSUE TITLE
Convert Agreements to HTML

### ISSUE THREAD

**Issue by hstriano** [Project-Rocket-IO/project-rocket-io.github.io#78]

**Comment by Langutang** [comment]
Do you want me to copy the current agreement we have from the website in here and you can replace the words for us?

**Comment by hstriano** [comment]
@Langutang 
All the agreements and HTML equivalents have been completed and are saved in the Rocket folder (https://drive.google.com/drive/folders/1s9IgeFjBNmCoc79igVlJQWk6hZFpRz4O)

Project Rocket PSA > Business & Legal > Legal Documents > HTML

Completed for Acceptable Use Policy, Disclaimer, End User License Agreement, Privacy Policy, and Terms of Use
